backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
collections:

  - name: 'Memorial Videos'
    label: 'Memorial Videos'
    folder: 'content/memorialBlock/'
    create: false
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Title on Video', name: 'ServiceOfSongs', widget: 'string' }
      - { label: 'youtubeId', name: 'youtubeId', widget: 'text' }
      - { label: 'Featured Image', name: 'image', widget: 'image' }

  - name: 'notable Reflection'
    label: 'Notable Reflection'
    folder: 'content/notableReflec/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Name of Person', name: 'pastorsName', widget: 'string' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }

  - name: 'Slider'
    label: 'Slider'
    folder: 'content/slideItems/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Name of Person', name: 'pastorsName', widget: 'string' }
      - { label: 'Slider image', name: 'image', widget: 'image' }

  - name: 'Testimony'
    label: 'Testimony'
    folder: 'content/testimony/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Name of Testifier', name: 'nameofTestifier', widget: 'string' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Testimony Heading', name: 'testimonyHeading', widget: 'text' }
      - { label: 'Featured Image', name: 'image', widget: 'image' }
      - { label: 'Summary Paragraph', name: 'summaryParagraph', widget: 'text' }
      - { label: 'META Title', name: 'seoTitle', widget: 'text' }
      - { label: 'META Description', name: 'seoDescription', widget: 'text' }
      - { label: 'META Image', name: 'imageOG', widget: 'image' }

  - name: 'Tributes'
    label: 'Tributes'
    folder: 'content/tributes/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Tribute Title', name: 'tributeTitle', widget: 'string' }
      - { label: 'Name of Person', name: 'pastorsName', widget: 'string' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Summary Heading', name: 'summaryHeading', widget: 'string' }
      - { label: 'Summary Content', name: 'summaryParagraph', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "categories"
        name: "categories"
        widget: "select"
        options:
           - { label: "missionary", value: "Missionary" }
           - { label: "Friend", value: "Friend" }
           - { label: "missionary", value: "Missionary" }
           - { label: "Family", value: "Family" }
           - { label: "Colleague", value: "Colleague" }

  - name: 'Pages'
    label: 'pages'
    files:
      - label : "About His life"
        name : "About His life"
        file : "/content/his-life.md"
        fields:
          - { label: 'title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'META Title', name: 'seoTitle', widget: 'text' }
          - { label: 'META Description', name: 'seoDescription', widget: 'text' }
          - { label: 'META Image', name: 'imageOG', widget: 'image' }

      - label : "Homepage"
        name : "Homepage"
        file : "/content/_index.md"
        fields:
          - { label: 'title', name: 'title', widget: 'string' }
          - { label: 'META Title', name: 'seoTitle', widget: 'text' }
          - { label: 'META Description', name: 'seoDescription', widget: 'text' }
          - { label: 'META Image', name: 'imageOG', widget: 'image' }
